version: 2

updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'x:size/small'
