version: '2.1'

services:
  app:
    extends:
      file: docker/common.yml
      service: app
    links:
      - db
    command: rerun -b --ignore='{**/*.{scss,css,js,coffee,erb},test/**}' 'puma -p 4567'
    ports:
      - "${EXTERNAL_PORT}:4567"
    environment:
      # These will ensure that certain development commands which
      # use 'psql' will also include our custom database config.
      #
      # For more information, see:
      # http://www.postgresql.org/docs/8.4/static/libpq-envars.html
      PGHOST: db
      PGUSER: exercism
      PGPASSWORD: apples

      RACK_ENV:
      DEV_DATABASE_HOST: db

  db:
    image: postgres:9.4
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: exercism
      POSTGRES_PASSWORD: apples

  compass:
    extends:
      file: docker/common.yml
      service: app
    command: compass watch

  lineman:
    extends:
      file: docker/common.yml
      service: app
    command: rerun -b --pattern '{**/*.coffee,**/{script,stats}.js}' -- lineman run
    working_dir: /exercism/frontend

volumes:
  pgdata:
    driver: local
